FROM golang:1.23

WORKDIR /personal/htmltopdfstorage/cmd
COPY go.mod .
RUN go mod tidy


RUN apt update
RUN apt upgrade
RUN apt install -y wkhtmltopdf 

COPY . .
RUN go build .


WORKDIR /personal/serve/cmd

COPY go.mod .
RUN go mod tidy

COPY . .
RUN go build .

EXPOSE 3000

CMD ["go", "run", "."]

